name: Run plugin workflow

on:
    pull_request:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    call-test-workflow:
        name: Run tests for SwagBackendOrder
        strategy:
            matrix:
                include:
                    -   shopware-version: '5.6'
                        php-version: '7.2'
                        mysql-version: '5.7'
                    -   shopware-version: '5.7'
                        php-version: '7.4'
                        mysql-version: '8.0'
                    -   shopware-version: '5.7'
                        php-version: '8.2'
                        mysql-version: '8.0'

        uses: shopware5/docker-images-testing/.github/workflows/php-unit-tests-shopware.yml@main
        with:
            plugin-name: SwagBackendOrder
            php-version: ${{ matrix.php-version }}
            shopware-version: ${{ matrix.shopware-version }}
            mysql-version: ${{ matrix.mysql-version }}

    call-analyse-workflow:
        name: Analyse code for SwagBackendOrder
        uses: shopware5/docker-images-testing/.github/workflows/php-code-analysis.yml@main
        with:
            plugin-name: SwagBackendOrder

    call-javascript-workflow:
        name: Analyse Javascript Code for SwagBackendOrder
        uses: shopware5/docker-images-testing/.github/workflows/javascript-analysis.yml@main
        with:
            plugin-name: SwagBackendOrder
